[package]
name = "rust-kinect-reprojection-app-bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kinect1 = {path = "../kinect1"}
anyhow = "1.0.66"
thiserror = "1.0"
image = "0.24.5"
array2d = "0.3"
itertools = "0.10.5"

# bevy = "0.9"
bevy = { version = "0.9", features = ["dynamic"] }
bevy_reflect = { version = "0.9" }
bevy_asset = { version = "0.9" }
bevy_render = { version = "0.9" }
bevy_framepace = "0.9"

bevy-inspector-egui = { version = "0.16.0-pre.2", default-features = false, features=["bevy_pbr"] }
egui = "0.20.0"
bevy_egui = "0.18"
egui_dock = "0.3"
egui-gizmo = { git = "https://github.com/matthiascy/egui-gizmo", rev = "516dc8453bb6423d8cf050af172e854611a8a1d9" }
rfd = "0.10.0"
bytemuck = "1.12.3"

# bevy-aabb-instancing = "0.7.0"
# smooth-bevy-cameras = "0.6.0"
bevy-aabb-instancing = { git = "https://github.com/foresightminingsoftwarecorporation/bevy-aabb-instancing" }
smooth-bevy-cameras = { git = "https://github.com/olegomon/smooth-bevy-cameras" }
