[package]
name = "kinect1-sys"
version = "0.1.0"
edition = "2021"
links = "Kinect10"

[dependencies]
bytemuck = "1.12.3"

[build-dependencies]
bindgen = "0.64.0"
# cc = { version = "1.0", features = ["parallel"] }
