[package]
name = "kinect1-sys"
version = "0.1.0"
edition = "2021"
# links = "kinect_helper"

[dependencies]


[build-dependencies]
bindgen = "0.63.0"
cc = { version = "1.0", features = ["parallel"] }
