[package]
name = "kinect1-cc"
version = "0.1.0"
edition = "2021"
links = "kinect_cc"

[dependencies]
kinect1-sys = {path = "../kinect1-sys"}

[build-dependencies]
kinect1-sys = {path = "../kinect1-sys"}
bindgen = "0.63.0"
cc = { version = "1.0", features = ["parallel"] }
