[package]
name = "rust-kinect-reprojection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kinect1 = {path = "../kinect1"}
anyhow = "1.0.66"
thiserror = "1.0"
image = "0.24.5"
minifb = "0.23"
