[package]
name = "kinect1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# kinect1-cc = {path = "../kinect1-cc"}
kinect1-sys = {path = "../kinect1-sys"}
winresult = "0.1.3"
thiserror = "1.0"
image = "0.24.5"
itertools = "0.10.5"
